version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://root:password@localhost:5432/db
    volumes:
      - .:/app
    depends_on: [database]
    ports:
      - "3000:3000"
    command: npm run dev

  database:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
