version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app
    depends_on: [database]
    ports:
      - "3000:3000"
    command: npm run dev

  database:
    image: postgres:14.5
    restart: always
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
